// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace ProjekatBilijar.Migrations
{
    [DbContext(typeof(BilijarKlubContext))]
    [Migration("20220316172428_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.BilijarKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojStolova")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxLjudiZaStolom")
                        .HasColumnType("int");

                    b.Property<int>("MaxLokala")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("BilijarKlub");
                });

            modelBuilder.Entity("Models.Narudzbina", b =>
                {
                    b.Property<int>("IDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BilijarKlubID")
                        .HasColumnType("int");

                    b.Property<string>("Pivo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sokovi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IDN");

                    b.HasIndex("BilijarKlubID");

                    b.ToTable("Narudzbina");
                });

            modelBuilder.Entity("Models.Sto", b =>
                {
                    b.Property<int>("IDStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BilijarKlubID")
                        .HasColumnType("int");

                    b.Property<int>("BrojStola")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaxBrojLjudi")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Stanje")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrenutniBrojLjudi")
                        .HasColumnType("int");

                    b.HasKey("IDStola");

                    b.HasIndex("BilijarKlubID");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("Models.Narudzbina", b =>
                {
                    b.HasOne("Models.BilijarKlub", "BilijarKlub")
                        .WithMany("Narudzbine")
                        .HasForeignKey("BilijarKlubID");

                    b.Navigation("BilijarKlub");
                });

            modelBuilder.Entity("Models.Sto", b =>
                {
                    b.HasOne("Models.BilijarKlub", "BilijarKlub")
                        .WithMany("Stolovi")
                        .HasForeignKey("BilijarKlubID");

                    b.Navigation("BilijarKlub");
                });

            modelBuilder.Entity("Models.BilijarKlub", b =>
                {
                    b.Navigation("Narudzbine");

                    b.Navigation("Stolovi");
                });
#pragma warning restore 612, 618
        }
    }
}
